#version 430

layout(local_size_x = 10, local_size_y = 10) in;

layout(std430, binding = 0) buffer PosIn
{
    vec3 PositionIn[];
};

void main()
{
    uvec3 NumParticles = gl_NumWorkGroups * gl_WorkGroupSize;
    uint Index = gl_GlobalInvocationID.y * NumParticles.x + gl_GlobalInvocationID.x;

    vec3 p = PositionIn[Index];

    PositionIn[Index] = vec3(p.x + sin(Index), p.y + cos(Index), p.z);
}